version: '3.8'

services:
  portfolio-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=portfolio-db;Database=PortfolioDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portfolio-db:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portfolio-redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portfolio-proxy:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portfolio-traefik:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure