version: '3.8'

services:
  portfolio-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=PortfolioDB;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Password123};TrustServerCertificate=true;
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - .:/src
      - ${APPDATA}/Microsoft/UserSecrets:/home/appuser/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/appuser/.aspnet/https:ro
    command: dotnet watch run --urls "https://+:443;http://+:80"

  portfolio-db:
    ports:
      - "1433:1433"

  portfolio-redis:
    ports:
      - "6379:6379"

  portfolio-proxy:
    profiles: ["production"]
    
  portfolio-traefik:
    profiles: ["production"]